# Generated by Django 5.1.5 on 2025-02-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_joblisting_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
